SELECT * FROM customer_shopping.mytable limit 20;


#what is the total revenue generated by male vs female  customers
select gender, sum(purchase_amount) as revenue from customer_shopping.mytable
group by gender;


#which customers used a discount but still more than the average purchase amount
select customer_id, purchase_amount from customer_shopping.mytable 
where discount_applied='Yes' and purchase_amount>= (Select avg(purchase_amount) from customer_shopping.mytable ) 


#which are top 5 products with the highest review ratings
select item_purchased, Round(Avg(review_rating),2) as "average product rating" from customer_shopping.mytable 
group by item_purchased 
order by avg(review_rating) 
limit 5;

#compare the average purchase accounts between standard and express shipping
select shipping_type, Round(avg(purchase_amount) ,2)
from customer_shopping.mytable 
where shipping_type in ('standard','Express')
group by shipping_type;

#Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non_subscribers.
select subscription_status, count(customer_id) as total_customers ,
avg(purchase_amount) as average_spend,
sum(purchase_amount) as total_revenue
from customer_shopping.mytable 
group by subscription_status
order by total_revenue, average_spend desc;

#which 5 products have the highest percentage of purchases with dicount applied
select item_purchased,
Round(100 * sum(Case When discount_applied='yes' Then 1 else 0 end) /count(*) ,2) as discount_rate 
from customer_shopping.mytable 
group by item_purchased
order by discount_rate desc;

#segement of customers into new,returning and loyal based on their total numer of previous purchases and show the count of each segements
 with customer_type as (
 select customer_id, previous_purchases,
 Case 
       when previous_purchases = 1 then 'New'
       when previous_purchases between 2 and 10 then 'returning'
       else 'Loyal'
       End as customer_segement 
from customer_shopping.mytable 
)
 select customer_segement ,count(*) as "number_of_customers"
 from customer_type
 group by customer_segement ;
 
 
 
 
 #what are the top 3 most purchased products within each category
 with item_count as(
 select category, item_purchased,
 count(customer_id)  as total_orders,
 ROW_NUMBER() over(partition by category order by count(customer_id) Desc) as item_rank
from customer_shopping.mytable 
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders 
from item_count
where item_rank <= 3;

#Are customers who repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers from customer_shopping.mytable 
where previous_purchases >=5
group by subscription_status;

#what are the revenue contribution for each group
select age_group, sum(purchase_amount) as total_revenue from customer_shopping.mytable 
group by age_group
order by total_revenue  desc;